### ISSUE TITLE
Support "Etag" header in addition to "X-Etag"

### ISSUE THREAD

**Issue by Otiel** [devlooped/dotnet-file#86]
It seems that dotnet-file only reads from `"X-Etag"` header, while some servers return the `"Etag"` header. It would be great if dotnet-file supported both headers.

**Comment by kzu** [comment]
Good suggestion!

Happy to take a PR :)

**Comment by Otiel** [comment]
I tried to tackle this when I created this issue but, as my development machine is located in an offline environment, I encountered an issue preventing me from building `File.sln`. If I remember correctly, I believe it is due to the fact that you are using a submodule to https://www.nuget.org/packages/git-credential-manager in `external`. Couldn't you use the [gcm nuget package](https://www.nuget.org/packages/git-credential-manager) directly?

I could try again once building is possible if only nuget packages are required.

**Comment by kzu** [comment]
Good idea. That package didn't exist when I started this project :)

Would you to try removing the module and replacing with the package to see how it goes? Happy to take that as part of another PR, if possible.

**Comment by kzu** [comment]
Notes on this:

1. The HEAD-only request with `X-ETag`+`X-Sha` is used as an optimization since I didn't find `IfNoneMatch` to work consistently with GH. 
2. The file request (besides the 1. optimization) is always run with `IfNoneMatch` [as a header](https://github.com/devlooped/dotnet-file/blob/main/src/File/AddCommand.cs#L121)
3.  A standard HTTP server should return `NotModified` status code in that case, which [is always checked](https://github.com/devlooped/dotnet-file/blob/main/src/File/AddCommand.cs#L135).

So I'm tentatively closing this, unless you have a concrete example (ideally a failing test?). Also, I did away with the submodule as recommended (it was a bit tricky), so it should be simpler to contribute now.

Thanks!

**Comment by Otiel** [comment]
Sorry, I didn't have time to tackle this before, and I moved away from `dotnet-file` in the meantime. I'll be sure to take a look at it and provide a failing test / PR the next time I have to use `dotnet-time`!

Thank you
